Repository AGH-Narzedzia-Informatyczne-2022-2023/programmers4u, pull requests merged in 2022-11, with the labels that each got.

#6 Am agh branch
  main_function.py
  settings.py
Labels: Label - projekt

#9 Pb branch
  save.py
Labels: bug, Label - projekt

#8 Jm branch
  obsluga_sterowania.py
Labels: Label - projekt

#10 Update README.md
  README.md
Labels: bug
